services:
    av_list:
        class: AppVentus\ListBundle\Component\AvListFactory
        arguments: ["@request_stack", "@templating", "@translator"]
        public: true

    av_list.twig.list_extension:
        class: AppVentus\ListBundle\Twig\Extension\ListExtension
        arguments: ["@twig"]
        tags:
            - { name: twig.extension }
